Courses_MVC/Courses_MVC/Models/ExerciseInUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Courses_MVC.Models
{
    public class ExerciseInUser
    {
        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Bài tập")]
        public int exerciseId { get; set; }

        
        public Exercise Exercise { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Tên người dùng")]
        public string userId { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Bài làm")]
        public string content { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        
        [Display(Name = "Tình trạng")]
        public string status { get; set; }

        public AppUser AppUser { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Nộp bài")]
        public DateTime submit { get; set; }

        [Display(Name = "Điểm")]
        [Range(0,10,ErrorMessage ="{0} phải nằm từ thang điểm 0 đến 10")]
        public float scores { get; set; }

    }
}

Courses_MVC/Courses_MVC/Controllers/ExerciseInUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Courses_MVC.Data;
using Courses_MVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Courses_MVC.Controllers
{
    [Authorize(Policy = "QuanTriVien")]
    public class ExerciseInUsersController : Controller
    {
        private readonly CoursesContext _context;

        private readonly UserManager<AppUser> _userManager;

        public ExerciseInUsersController(CoursesContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        // GET: ExerciseInUsers
        public async Task<IActionResult> DanhSachBTUser()
        {
            
            var exerciseInUser = _context.ExerciseInUsers.Include(e => e.AppUser).Include(e => e.Exercise);
            var count = exerciseInUser.Count();
            ViewData["count"] = count;
            return View(await exerciseInUser.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DanhSachBTUser(string search)
        {
            var exerciseInUser = from exInUs in _context.ExerciseInUsers select exInUs;
            var count = exerciseInUser.Count();
            
            if (!string.IsNullOrEmpty(search))
            {
                exerciseInUser = exerciseInUser.Where(c => c.AppUser.UserName.Contains(search)).Include(c => c.AppUser).Include(c => c.Exercise);
                count = exerciseInUser.Count();
            }
            else
            {
                exerciseInUser = exerciseInUser.Include(c => c.AppUser).Include(c => c.Exercise);
                count = exerciseInUser.Count();
            }
            ViewData["count"] = count;
            return View(await exerciseInUser.ToListAsync());
        }

        public IActionResult ThemSVBT()
        {
            var user = _context.Users.ToList();
            user.Insert(0, new AppUser() {
                Id = "",
                UserName = ""
            });
            ViewData["userId"] = new SelectList(user, "Id", "UserName");

            var exercise = _context.Exercises.ToList();
            exercise.Insert(0, new Exercise()
            {
                exerciseId = 0,
                exerciseName = ""
            }) ;
            ViewData["exerciseId"] = new SelectList(exercise, "exerciseId", "exerciseName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ThemSVBT(ExerciseInUser exerciseInUser)
        {
            var user = _context.Users.ToList();
            user.Insert(0, new AppUser()
            {
                Id = "",
                UserName = ""
            });
            ViewData["userId"] = new SelectList(user, "Id", "UserName");

            var exercise = _context.Exercises.ToList();
            exercise.Insert(0, new Exercise()
            {
                exerciseId = 0,
                exerciseName = ""
            });
            ViewData["exerciseId"] = new SelectList(exercise, "exerciseId", "exerciseName");
            if (exerciseInUser == null)
            {
                return NotFound();
            }
            if(exerciseInUser.userId.ToString() == "")
            {
                ModelState.AddModelError(string.Empty, "Phải chọn sinh viên");
            }
            if (exerciseInUser.exerciseId == 0)
            {
                ModelState.AddModelError(string.Empty, "Phải chọn bài học");
            }
            if (ModelState.IsValid)
            {
                _context.ExerciseInUsers.Add(new ExerciseInUser() { 
                    userId = exerciseInUser.userId,
                    exerciseId = exerciseInUser.exerciseId,
                    scores = exerciseInUser.scores,
                    submit = exerciseInUser.submit,
                    content = exerciseInUser.content,
                    status = exerciseInUser.status
                });
                _context.SaveChanges();
                StatusMessage = $"Thêm thành công ";
                return RedirectToAction(nameof(DanhSachBTUser));
            }
            StatusMessage = "Thêm không thành công";
            return View();
        }

        // GET: ExerciseInUsers/Details/5
        public async Task<IActionResult> ChiTietBTUser(int exerciseId, string userId)
        {
            if (exerciseId == 0 && userId == null)
            {
                return NotFound();
            }

            var result = await _context.ExerciseInUsers
                .Where(c => c.userId == userId).Include(e => e.AppUser).Include(e => e.Exercise).Where(c => c.exerciseId == exerciseId).FirstOrDefaultAsync();
            //ViewData["userId"] = new SelectList(_context.Users, "Id", "UserName", result.userId );
            //ViewData["exerciseId"] = new SelectList(_context.Exercises, "exerciseId", "exerciseName", result.exerciseId);
            if (result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        public async Task<IActionResult> CapNhatBTUser(int exerciseId, string userId)
        {
            if (exerciseId == 0 && userId == null)
            {
                return NotFound();
            }

            var result = await _context.ExerciseInUsers
                .Where(c => c.userId == userId).Include(e => e.AppUser).Include(e => e.Exercise).Where(c => c.exerciseId == exerciseId).FirstOrDefaultAsync();
            ViewData["userId"] = new SelectList(_context.Users, "Id", "UserName", result.userId);
            ViewData["exerciseId"] = new SelectList(_context.Exercises, "exerciseId", "exerciseName", result.exerciseId);
            if (result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> CapNhatBTUser(ExerciseInUser exerciseInUser)
        {
            if (exerciseInUser.exerciseId == 0 && exerciseInUser.userId == null)
            {
                return NotFound();
            }
            var result =await _context.ExerciseInUsers
                .Where(c => c.userId == exerciseInUser.userId).Include(e => e.AppUser).Include(e => e.Exercise).Where(c => c.exerciseId == exerciseInUser.exerciseId).FirstOrDefaultAsync();


            if (result == null)
            {
                StatusMessage = "Cập nhật không thành công";
                return RedirectToAction(nameof(DanhSachBTUser));
            }
            else
            {
                //result.userId = exerciseInUser.userId;
                //result.exerciseId = exerciseInUser.exerciseId;
                result.scores = exerciseInUser.scores;
                result.submit = exerciseInUser.submit;
                result.content = exerciseInUser.content;
                result.status = exerciseInUser.status;
                _context.SaveChanges();
                StatusMessage = $"Cập nhật thành công ";
                return RedirectToAction(nameof(DanhSachBTUser));

            }


        }

        public IActionResult XoaBTUser(int exerciseId, string userId)
        {
            if(exerciseId == 0 && userId == null)
            {
                return NotFound();
            }
            var topic = _context.ExerciseInUsers.Where(c=>c.userId == userId).Where(c=>c.exerciseId == exerciseId).FirstOrDefault();
            if (topic == null)
            {
                return NotFound();
            }
            _context.Remove(topic);
            _context.SaveChanges();
            StatusMessage = $"Xóa thành công ";
            return RedirectToAction(nameof(DanhSachBTUser));
        }


        public IActionResult SubmitExercise(int lessonId,int exerciseId, string content)
        {
            var user = _userManager.GetUserId(User);
            int curentlessonId = lessonId;
            if (content == null)
            {
                ModelState.AddModelError(string.Empty, "Chưa có nội dung bài làm");
            }
            _context.ExerciseInUsers.Add(new ExerciseInUser()
            {
                userId = user,
                exerciseId = exerciseId,
                content = content,
                submit = DateTime.Now
            }) ;
            _context.SaveChanges();
            StatusMessage = $"Nộp bài tập thành công";
            return RedirectToAction("LessonDetail", "lesson", new { id = curentlessonId });
        }



        private bool ExerciseInUserExists(string id)
        {
            return _context.ExerciseInUsers.Any(e => e.userId == id);
        }
    }
}

Courses_MVC/Courses_MVC/Views/ExerciseInUsers/CapNhatBTUser.cshtml
@model Courses_MVC.Models.ExerciseInUser
@{
    ViewData["Title"] = "Cập nhập sinh viên làm bài tập";
}

<div class="main">
        <partial name="_NavBar" />
        <div class="col-md-8">
            <partial name="_AlertMessage" />
            <h2 class="contact-title text-center">@ViewData["Title"]</h2>
            <form action="" class="col-md-10 offset-md-2 mt-5" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mt-3">
                    <label asp-for="userId" class="control-label"></label>
                    <select asp-for="userId" class="form-control" asp-items="ViewBag.userId" disabled></select>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="exerciseId" class="control-label"></label>
                    <select asp-for="exerciseId" class="form-control" asp-items="ViewBag.exerciseId" disabled></select>
                    <span asp-validation-for="exerciseId" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="submit" class="control-label"></label>
                    <input asp-for="submit" class="form-control" />
                    <span asp-validation-for="submit" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="scores" class="control-label"></label>
                    <input asp-for="scores" class="form-control" />
                    <span asp-validation-for="scores" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="content" class="control-label"></label>
                    <textarea asp-for="content" class="form-control" id="content"></textarea>
                    <span asp-validation-for="content" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label asp-for="status" class="control-label"></label>
                    <select asp-for="status" class="form-control">
                        <option value="Chưa chấm điểm">Chưa chấm điểm</option>
                        <option value="Đã chấm điểm">Đã chấm điểm</option>
                    </select>
                </div>
                <div class="form-row mb-4">
                    <div class="form-group col-md-6">
                        <input type="submit" name="submit" value="Cập nhật" class="btn btn-primary btn-block" />
                    </div>
                    <div class="form-group col-md-6">
                        <a asp-action="DanhSachBTUer" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Trở về</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
@{
    var summernote = new Courses_MVC.Models.Summernote("#content");

}
<partial name="_Summernote" model="summernote" />
<script>
    const active_lienhe = document.querySelector('#active--SV_BT')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/ExerciseInUsers/ChiTietBTUser.cshtml
@model Courses_MVC.Models.ExerciseInUser
@{
    ViewData["Title"] = "Chi tiết sinh viên làm bài tập";
}

<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">@ViewData["Title"]</h1>
        <div class="ml-5">
            <div class="">
                <hr />

                <dl class="row">
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.exerciseId)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.exerciseId)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.AppUser.UserName)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.AppUser.UserName)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.submit)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.submit)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.scores)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.scores)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.content)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.content)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.status)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.status)
                    </dd>
                </dl>
            </div>
            <div class="option-detail">

                <div class="back-admin">
                    <a asp-action="DanhSachBTUser">Danh sách sinh viên làm bài tập</a>
                </div>
                <div class="main-option">
                    <a asp-action="CapNhatBTUser" asp-route-exerciseId="@Model.exerciseId" asp-route-userId="@Model.userId">Chỉnh sửa</a>
                </div>

            </div>
        </div>
    </section>
</main>


@{
    var summernote = new Courses_MVC.Models.Summernote("#content");

}
<partial name="_Summernote" model="summernote" />
<script>
    const active_lienhe = document.querySelector('#active--SV_BT')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/ExerciseInUsers/DanhSachBTUser.cshtml
@model IEnumerable<Courses_MVC.Models.ExerciseInUser>
@{
    ViewData["Title"] = "Danh sách sinh viên làm bài tập";
}

<main class="main">
    <partial name="_NavBar" />
    <section>
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">@ViewData["Title"]</h1>
        <p class="count--css">Số lượng sinh viên làm bài tập: @ViewBag.count</p>
        <div class="search-create">
            <form action="" method="post">
                <div class="form-inline">
                    <label class="control-label" style="margin-right: 5px;">Tìm kiếm sinh viên</label>
                    <input type="text" name="search" class="form-control col-md-5">
                    <input type="submit" class="btn btn-info" name="submit" value="search">

                </div>
            </form>
            <div>
                <a asp-controller="ExerciseInUsers" asp-action="ThemSVBT" class="btn btn-outline-success"><i class="far fa-plus-square"></i> Thêm</a>
            </div>
        </div>
        <div class="table-overflow">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            STT
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AppUser.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Exercise.exerciseName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.submit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.scores)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.status)
                        </th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td class="counterCell">
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AppUser.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Exercise.exerciseName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.submit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.scores)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.status)
                        </td>
                        <td>
                            <a asp-action="ChiTietBTUser" asp-route-exerciseId="@item.exerciseId" asp-route-userId="@item.userId"><i class="far fa-edit"></i></a> |
                            <a asp-action="XoaBTUser" asp-route-exerciseId="@item.exerciseId" asp-route-userId="@item.userId" class="text-danger" onclick="return confirm('Bạn chắn chắn xóa chứ?')"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>

    </section>
</main>
<script>
    const active_lienhe = document.querySelector('#active--SV_BT')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/ExerciseInUsers/ThemSVBT.cshtml
@model Courses_MVC.Models.ExerciseInUser
@{
    ViewData["Title"] = "Thêm sinh viên làm bài tập";
}

<div class="main">
    <partial name="_NavBar" />
    <div class="col-md-8">
        <partial name="_AlertMessage" />
        <h2 class="contact-title text-center">@ViewData["Title"]</h2>
        <form asp-action="ThemSVBT" class="col-md-10 offset-md-2 mt-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-3">
                <label asp-for="userId" class="control-label"></label>
                <select asp-for="userId" class="form-control" asp-items="ViewBag.userId"></select>
            </div>
            <div class="form-group mt-3">
                <label asp-for="exerciseId" class="control-label"></label>
                <select asp-for="exerciseId" class="form-control" asp-items="ViewBag.exerciseId"></select>
            </div>
            <div class="form-group mt-3">
                <label asp-for="submit" class="control-label"></label>
                <input asp-for="submit" class="form-control" />
                <span asp-validation-for="submit" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="scores" class="control-label"></label>
                <input asp-for="scores" class="form-control" />
                <span asp-validation-for="scores" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="content" class="control-label"></label>
                <textarea asp-for="content" class="form-control" id="content"></textarea>
                <span asp-validation-for="content" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="status" class="control-label"></label>
                <select asp-for="status" class="form-control">
                    <option value="Chưa chấm điểm">Chưa chấm điểm</option>
                    <option value="Đã chấm điểm">Đã chấm điểm</option>
                </select>
            </div>
            <div class="form-row mb-4">
                <div class="form-group col-md-6">
                    <input type="submit" name="submit" value="Thêm" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="DanhSachBTUser" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Trở về</a>
                </div>
            </div>

        </form>
    </div>
</div>
@{
    var summernote = new Courses_MVC.Models.Summernote("#content");

}
<partial name="_Summernote" model="summernote" />

<script>
    const active_lienhe = document.querySelector('#active--SV_BT')

    active_lienhe.classList.add('active--css')
    document.querySelector('#active--khoahoc').classList.remove('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}