Courses_MVC/Courses_MVC/Models/Receipt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Courses_MVC.Models
{

    public class Receipt
    {
        public int receiptId { get; set; }

        [Display(Name = "Tổng tiền")]
        public float totalPrice { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Thời gian đăng kí")]
        public DateTime timeReceipt { get; set; }

        [Required(ErrorMessage = "Phải nhập {0}")]
        [Display(Name = "Đăng kí")]
        public int registerId { get; set; }

        public Register Register { get; set; }
    }
}

Courses_MVC/Courses_MVC/Controllers/ReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Courses_MVC.Data;
using Courses_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Courses_MVC.Controllers
{
    [Authorize(Policy = "QuanTriVien")]
    public class ReceiptsController : Controller
    {
        private readonly CoursesContext _context;

        public ReceiptsController(CoursesContext context)
        {
            _context = context;
        }
        [TempData]
        public string StatusMessage { get; set; }
        // GET: Receipts
        public async Task<IActionResult> DanhSachHoaDon()
        {
            var receiptContext = _context.Receipts.Include(r => r.Register);
            var count = receiptContext.Count();
            ViewData["count"] = count;
            return View(await receiptContext.ToListAsync());
        }

        

        // GET: Receipts/Details/5
        public async Task<IActionResult> ChiTietHoaDon(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .Include(r => r.Register)
                .FirstOrDefaultAsync(m => m.receiptId == id);
            if (receipt == null)
            {
                return NotFound();
            }

            return View(receipt);
        }

        public async Task<IActionResult> CapNhatHoaDon(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .Include(r => r.Register)
                .FirstOrDefaultAsync(m => m.receiptId == id);
            if (receipt == null)
            {
                return NotFound();
            }

            return View(receipt);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CapNhatHoaDon(int? id, Receipt receipt)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await _context.Receipts
                .Include(r => r.Register)
                .FirstOrDefaultAsync(m => m.receiptId == id);
            if (result != null)
            {
                
                result.totalPrice = receipt.totalPrice;
                result.timeReceipt = receipt.timeReceipt;
                _context.SaveChanges(); 
                StatusMessage = $"Cập nhật thành công";
                return RedirectToAction(nameof(DanhSachHoaDon));
            }
            else
            {
                StatusMessage = $"Cập nhật không thành công ";
                return RedirectToAction(nameof(DanhSachHoaDon));
            }
        }

        // GET: Receipts/Create
        public IActionResult ThemHoaDon()
        {
            ViewData["registerId"] = new SelectList(_context.Registers, "registerId", "registerId");
            return View();
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ThemHoaDon(Receipt receipt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(receipt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(DanhSachHoaDon));
            }
            ViewData["registerId"] = new SelectList(_context.Registers, "registerId", "registerId", receipt.registerId);
            StatusMessage = $"Thêm thành công hóa đơn";
            return View(receipt);
        }

        
        
        

        // GET: Receipts/Delete/5
        public async Task<IActionResult> XoaHoaDon(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .Include(r => r.Register)
                .FirstOrDefaultAsync(m => m.receiptId == id);
            if (receipt == null)
            {
                StatusMessage = $"Xóa không thành công ";
                return RedirectToAction(nameof(DanhSachHoaDon));
            }
            _context.Receipts.Remove(receipt);
            await _context.SaveChangesAsync();
            StatusMessage = $"Xóa thành công hóa đơn có mã hóa đơn là {receipt.receiptId}";
            return RedirectToAction(nameof(DanhSachHoaDon));
        }

        
        private bool ReceiptExists(int id)
        {
            return _context.Receipts.Any(e => e.receiptId == id);
        }
    }
}

Courses_MVC/Courses_MVC/Views/Receipts/CapNhatHoaDon.cshtml
@model Courses_MVC.Models.Receipt
@{
    ViewData["Title"] = "Cập nhật hóa đơn";

}

<div class="main">
    <partial name="_NavBar" />
    <div class="col-md-8">
        <partial name="_AlertMessage" />
        <h2 class="contact-title text-center">@ViewData["Title"]</h2>
        <form asp-action="CapNhatHoaDon" class="col-md-10 offset-md-2 mt-5" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-3">
                <label asp-for="receiptId" class="control-label"></label>
                <input asp-for="receiptId" class="form-control" disabled />
            </div>
            <div class="form-group mt-3">
                <label asp-for="registerId" class="control-label"></label>
                <input asp-for="registerId" class="form-control" disabled />
            </div>
            <div class="form-group mt-3">
                <label asp-for="totalPrice" class="control-label"></label>
                <input asp-for="totalPrice" class="form-control" />
                <span asp-validation-for="totalPrice" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="timeReceipt" class="control-label"></label>
                <input asp-for="timeReceipt" class="form-control" />
                <span asp-validation-for="timeReceipt" class="text-danger"></span>
            </div>
            <div class="form-row mb-4">
                <div class="form-group col-md-6">
                    <input type="submit" name="submit" value="Cập nhật" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="DanhSachHoaDon" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Danh sách đăng kí</a>
                </div>
            </div>

        </form>
    </div>
</div>

<script>
    const active_lienhe = document.querySelector('#active--giamgia')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Receipts/ChiTietHoaDon.cshtml
@model Courses_MVC.Models.Receipt
@{
    ViewData["Title"] = "Chi tiết hóa đơn";

}

<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">@ViewData["Title"]</h1>
        <div class="ml-5">
            <div class="">
                <hr />

                <dl class="row">
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.receiptId)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.receiptId)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.registerId)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.registerId)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.totalPrice)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.totalPrice)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => model.timeReceipt)
                    </dt>
                    <dd class="col-sm-9">
                        @Html.DisplayFor(model => model.timeReceipt)
                    </dd>

                </dl>
            </div>
            <div class="option-detail">

                <div class="back-admin">
                    <a asp-action="DanhSachHoaDon">Danh sách hóa đơn</a>
                </div>
                <div class="main-option">
                    <a asp-action="CapNhatHoaDon" asp-route-id="@Model.receiptId">Chỉnh sửa</a>
                </div>

            </div>
        </div>
    </section>
</main>



<script>
    const active_lienhe = document.querySelector('#active--hoadon')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Receipts/DanhSachHoaDon.cshtml
@model IEnumerable<Courses_MVC.Models.Receipt>
@{
    ViewData["Title"] = "Danh sách hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="main">
    <partial name="_NavBar" />
    <section>
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">@ViewData["Title"]</h1>
        <p class="count--css">Số lượng đăng kí: @ViewBag.count</p>
        <div class="search-create">
            
            <div>
                <a asp-controller="Receipts" asp-action="ThemHoaDon" class="btn btn-outline-success"><i class="far fa-plus-square"></i> Thêm</a>
            </div>
        </div>
        <div class="table-overflow">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            STT
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.registerId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.totalPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.timeReceipt)
                        </th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="counterCell">
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.registerId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.totalPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.timeReceipt)
                            </td>
                            <td>
                                <a asp-action="ChiTietHoaDon" asp-route-id="@item.receiptId"><i class="far fa-edit"></i></a> |
                                <a asp-action="XoaHoaDon" asp-route-id="@item.receiptId" class="text-danger" onclick="return confirm('Bạn chắn chắn xóa chứ?')"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </section>
</main>
<script>
    const active_lienhe = document.querySelector('#active--hoadon')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Receipts/ThemHoaDon.cshtml
@model Courses_MVC.Models.Receipt
@{
    ViewData["Title"] = "Thêm hóa đơn";
}
<div class="main">
    <partial name="_NavBar" />
    <div class="col-md-8">
        <partial name="_AlertMessage" />
        <h2 class="contact-title text-center">@ViewData["Title"]</h2>
        <form asp-action="ThemHoaDon" class="col-md-10 offset-md-2 mt-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-3">
                <label asp-for="registerId" class="control-label"></label>
                <select asp-for="registerId" class="form-control" asp-items="ViewBag.registerId"></select>
            </div>
            <div class="form-group mt-3">
                <label asp-for="totalPrice" class="control-label"></label>
                <input asp-for="totalPrice" class="form-control" />
                <span asp-validation-for="totalPrice" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="timeReceipt" class="control-label"></label>
                <input asp-for="timeReceipt" class="form-control" />
                <span asp-validation-for="timeReceipt" class="text-danger"></span>
            </div>
            <div class="form-row mb-4">
                <div class="form-group col-md-6">
                    <input type="submit" name="submit" value="Thêm" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="DanhSachHoaDon" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Trở về</a>
                </div>
            </div>

        </form>
    </div>
</div>


<script>
    const active_lienhe = document.querySelector('#active--dangki')

    active_lienhe.classList.add('active--css')
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}