Courses_MVC/Courses_MVC/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Courses_MVC.Data;
using Courses_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Courses_MVC.Controllers
{
    public class ExercisesController : Controller
    {
        private readonly CoursesContext _context;

        public ExercisesController(CoursesContext context)
        {
            _context = context;
        }

        [TempData]
        public string StatusMessage { get; set; }

        [Authorize(Policy = "QuanTriVien")]
        public async Task<IActionResult> ListExerciseAdmin()
        {
            var listExercises = await _context.Exercises.Include(e => e.AppUser).Include(e => e.Lesson).ToListAsync();
            var count = listExercises.Count();
            ViewData["count"] = count;
            return View(listExercises);
        }

        [Authorize(Policy = "QuanTriVien")]
        [HttpPost]
        public async Task<IActionResult> ListExerciseAdmin(string? searchString)
        {
            var listExercises = _context.Exercises.Include(e => e.AppUser).Include(e => e.Lesson);
            var count = listExercises.Count();
            
            if (!string.IsNullOrEmpty(searchString))
            {
                listExercises = listExercises.Where(e => e.Lesson.title.Contains(searchString)).Include(e => e.AppUser).Include(e => e.Lesson);
                count = listExercises.Count();
            }
            else
            {
                StatusMessage = $"Không tìm thấy";
                listExercises = _context.Exercises.Include(e => e.AppUser).Include(e => e.Lesson);
                count = listExercises.Count();
            }
            ViewData["count"] = count;
            return View(await listExercises.ToListAsync());
        }

        // GET: Exercises/Details/5
        public async Task<IActionResult> DetailsInUI(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var exercise = await _context.Exercises
                .Include(e => e.AppUser)
                .Include(e => e.Lesson)
                .FirstOrDefaultAsync(m => m.exerciseId == id);
            if (exercise == null)
            {
                return NotFound();
            }
            var listId = _context.Exercises
                           .Include(e => e.Lesson)
                           .Include(e => e.AppUser)
                           .Where(e => e.lessonId == exercise.lessonId)
                           .ToList();
            ViewBag.listIdExercise = listId.ToArray();
            return View(exercise);
        }

        [Authorize(Policy = "QuanTriVien")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises
                .Include(e => e.AppUser)
                .Include(e => e.Lesson)
                .FirstOrDefaultAsync(m => m.exerciseId == id);
            if (exercise == null)
            {
                return NotFound();
            }

            return View(exercise);
        }

        [Authorize(Policy = "QuanTriVien")]
        public IActionResult CreateExercise()
        {
            ViewData["userId"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["lessonId"] = new SelectList(_context.Lessons, "lessonId", "title");
            return View();
        }
        [HttpPost]
        [Authorize(Policy = "QuanTriVien")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateExercise(Exercise exer)
        {
            if (ModelState.IsValid)
            {
                _context.Exercises.Add(exer);
                _context.SaveChanges();
                StatusMessage = $"Thêm thành công";
                return RedirectToAction(nameof(ListExerciseAdmin));
            }
            else
            {
                StatusMessage = $"Thêm không thành công";
                return RedirectToAction(nameof(ListExerciseAdmin));
            }
            ViewData["userId"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["lessonId"] = new SelectList(_context.Lessons, "lessonId", "title");
            return View(exer);
        }

        [Authorize(Policy = "QuanTriVien")]
        public IActionResult UpdateExercise(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var exercise = _context.Exercises.FirstOrDefault(e => e.exerciseId == id);
            if (exercise == null)
            {
                return NotFound();
            }
            ViewData["userId"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["lessonId"] = new SelectList(_context.Lessons, "lessonId", "title");
            return View(exercise);
        }


        [HttpPost]
        [Authorize(Policy = "QuanTriVien")]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateExercise(Exercise exercise)
        {
            if(exercise.exerciseId == 0)
            {
                return NotFound();
            }
            var exerUpdate = _context.Exercises.Include(c=>c.AppUser).FirstOrDefault(e => e.exerciseId == exercise.exerciseId);
            var idlesson = exercise.lessonId;
            if (exerUpdate != null)
            {
                exerUpdate.exerciseName = exercise.exerciseName;
                exerUpdate.content = exercise.content;
                exerUpdate.input = exercise.input;
                exerUpdate.output = exercise.output;
                exerUpdate.deadline = exercise.deadline;
                exerUpdate.userId = exercise.userId;
                exerUpdate.lessonId = exerUpdate.lessonId;

                _context.SaveChanges();
                StatusMessage = $"Cập nhật thành công";
                return RedirectToAction(nameof(ListExerciseAdmin));
            }
            else
            {
                StatusMessage = $"Cập nhật không thành công";
                return RedirectToAction(nameof(ListExerciseAdmin));
            }
        }

        [Authorize(Policy = "QuanTriVien")]
        public IActionResult DeleteExercise(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var exercise = _context.Exercises.Include(e => e.Lesson).Include(e => e.AppUser).FirstOrDefault(e => e.exerciseId == id);
            if (exercise == null)
            {
                return NotFound();
            }
            return View(exercise);
        }

        [HttpPost, ActionName("DeleteExercise")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "QuanTriVien")]
        public IActionResult DeleteExerciseConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var execiseDelete = _context.Exercises.FirstOrDefault(e => e.exerciseId == id);
            _context.Exercises.Remove(execiseDelete);
            _context.SaveChanges();
            StatusMessage = $"Xóa thành công";
            return RedirectToAction(nameof(ListExerciseAdmin));

        }
  

        private bool ExerciseExists(int id)
        {
            return _context.Exercises.Any(e => e.exerciseId == id);
        }
    }
}

Courses_MVC/Courses_MVC/Views/Exercises/CreateExercise.cshtml
@model Courses_MVC.Models.Exercise

@{
    ViewData["Title"] = "Thêm bài luyện tập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">Thêm bài luyện tập</h1>
        <div class="p-4">
            <form asp-action="CreateExercise">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="exerciseName" class="control-label"></label>
                    <input asp-for="exerciseName" class="form-control" />
                    <span asp-validation-for="exerciseName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="content" class="control-label"></label>
                    <textarea asp-for="content" class="form-control" required rows="5" id="content"></textarea>
                    <span asp-validation-for="content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="input" class="control-label"></label>
                    <textarea asp-for="input" class="form-control" required rows="5" id="input"></textarea>
                    <span asp-validation-for="input" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="output" class="control-label"></label>
                    <textarea asp-for="output" class="form-control" required rows="5" id="output"></textarea>
                    <span asp-validation-for="output" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="deadline" class="control-label"></label>
                    <input asp-for="deadline" class="form-control" />
                    <span asp-validation-for="deadline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lessonId" class="control-label"></label>
                    <select asp-for="lessonId" class="form-control" asp-items="ViewBag.lessonId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="userId" class="control-label"></label>
                    <select asp-for="userId" class="form-control" asp-items="ViewBag.userId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Thêm" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </section>
</main>
@{
    var summernote = new Courses_MVC.Models.Summernote("#content");
    var input = new Courses_MVC.Models.Summernote("#input", false);
    var output = new Courses_MVC.Models.Summernote("#output", false);

}
<partial name="_Summernote" model="summernote" />
<partial name="_Summernote" model="input" />
<partial name="_Summernote" model="output" />

<script>
    const active_lienhe = document.querySelector('#active--baitap')
    active_lienhe.classList.add('active--css')
    /*document.querySelector('#active--khoahoc').classList.remove('active--css')*/
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Exercises/DeleteExercise.cshtml
@model Courses_MVC.Models.Exercise

@{
    ViewData["Title"] = "Xóa bài luyện tập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">Xóa bài luyện tập</h1>
        <div class="ml-5">
            <div>
                <h4>Bài tập</h4>
                <hr />
                <dl class="row">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.content)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.content)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.deadline)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.deadline)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Lesson.title)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Lesson.title)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.AppUser.UserName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.AppUser.UserName)
                        </dd>
                    </dl>
                </dl>
                <form asp-action="DeleteExercise">
                    <input type="hidden" asp-for="exerciseId" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <div class="back-admin">
                        <a asp-action="ListExerciseAdmin">Back to List</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main>
<script>
    const active_lienhe = document.querySelector('#active--baitap')
    active_lienhe.classList.add('active--css')
    /*document.querySelector('#active--khoahoc').classList.remove('active--css')*/
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Exercises/Details.cshtml
@model Courses_MVC.Models.Exercise

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">Chi tiết bài luyện tập</h1>
        <div class="ml-5">
            <div class="content-option">
                <h4>Bài luyện tập</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.exerciseId)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.exerciseId)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.exerciseName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.exerciseName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.content)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.content)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.input)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.input)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.output)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.output)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.deadline)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.deadline)
                    </dd>
                    <dt class="col-sm-2">
                        Bài học
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Lesson.title)
                    </dd>
                    <dt class="col-sm-2">
                        Tác giả
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.AppUser.UserName)
                    </dd>
                </dl>
            </div>
            <div class="option-detail">
                <div class="back-admin">
                    <a asp-action="ListExerciseAdmin">Trở về</a>
                </div>
                <div class="main-option">
                    <a asp-action="UpdateExercise" asp-route-id="@Model.exerciseId">Chỉnh sửa</a> 
                </div>

            </div>
        </div>
    </section>
</main>
<script>
    const active_lienhe = document.querySelector('#active--baitap')
    active_lienhe.classList.add('active--css')
    /*document.querySelector('#active--khoahoc').classList.remove('active--css')*/
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Exercises/DetailsInUI.cshtml
@using Microsoft.AspNetCore.Identity
@using Courses_MVC.Models
@using Microsoft.AspNetCore.Authorization
@model Exercise
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@{
    var listId = ViewBag.listIdExercise;
    var idcurrent = Model.exerciseId;
    var length = listId.Length;
    var idMin = listId[0].exerciseId;
    var idMax = listId[length - 1].exerciseId;
    var idPre = idcurrent - 1;
    var idNext = idcurrent + 1;
}
<link href="~/css/LessonDetail.css" rel="stylesheet" />
<div class="container col-9 container-custom mb-5">
    <partial name="_AlertMessage" />
    <div class="lesson-title mt-4 p-4 pb-2 text-center ">@Model.exerciseName</div>
    <div class="lesson-info pb-2 pt-3 p-4">
        <div class="lesson-info-teacher"><i class="fas fa-chalkboard-teacher"></i><b>Tác giả:</b> @Model.AppUser.UserName</div>
        <div class="lesson-info-deadline"><i class="fas fa-hourglass-start">Deadline:</i> @Model.deadline</div>
    </div>
    <div class="lesson-content mb-3 pl-4 pr-4">
        <b>Nội dung:</b>
        <p>
            @Model.content
        </p>
    </div>
    <div class="exercise-input mb-1 pl-4 pr-4">
        <b>Input:</b>
        <div>@Model.input</div>
    </div>
    <div class="exercise-output mb-1 pl-4 pr-4">
        <b>Output:</b>
        @Model.output
    </div>
    <div class="do-exercise mb-3 pl-4 pr-4">
        <form action="/ExerciseInUsers/SubmitExercise" method="post">
            <input type="hidden" name="exerciseId" value="@Model.exerciseId" />
            <input type="hidden" name="lessonId" value="@Model.lessonId" />

            <label for="place-do-exercise"><b>Làm bài tập:</b></label>
            <textarea name="content"
                      id="place-do-exercise"
                      cols="30" rows="10" placeholder="Nhập bài làm của bạn"
                      class="form-control"
                      required>

            </textarea>
            <span asp-validation-for="content" class="text-danger"></span>
            <button class="btn btn-primary" type="submit">Nộp bài</button>
        </form>

    </div>
    

    <div class="move-lesson p-4 pt-0">

        @if (idPre == idMin - 1)
        {
            <div class="next-lesson">
                <a href="/lesson/LessonDetail?Id=@Model.lessonId" class="pre-lesson-btn">Quay lại bài học</a>
            </div>
            <div class="pre-lesson">
                <a href="/Exercises/DetailsInUI?Id=@idNext" class="pre-lesson-btn">Kế tiếp</a>
            </div>
        }
        else if (idNext == idMax + 1)
        {
            <div class="next-lesson">
                <a href="/Exercises/DetailsInUI?Id=@idPre" class="pre-lesson-btn">Quay lại</a>
            </div>
            <div class="next-lesson">
                <a href="/lesson/LessonDetail?Id=@Model.lessonId" class="pre-lesson-btn">Quay lại bài học</a>
            </div>
        }
        else
        {
            <div class="next-lesson">
                <a href="/Exercises/DetailsInUI?Id=@idPre" class="pre-lesson-btn">Quay lại</a>
            </div>
            <div class="pre-lesson">
                <a href="/Exercises/DetailsInUI?Id=@idNext" class="pre-lesson-btn">Kế tiếp</a>
            </div>
        }
    </div>
</div>

Courses_MVC/Courses_MVC/Views/Exercises/ListExerciseAdmin.cshtml
@model IEnumerable<Courses_MVC.Models.Exercise>

@{
    ViewData["Title"] = "Danh sách bài luyện tập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-courseadmin">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">@ViewData["Title"]</h1>
        <p class="count--css">Số lượng khóa học: @ViewBag.count</p>
        <div class="search-create">
            <form action="/Exercises/listExerciseAdmin" method="post">
                <div class="form-inline ">
                    <label class="control-label " style="margin-right: 5px;">Tìm kiếm</label>
                    <input type="text" name="searchString" class="form-control col-md-6">
                    <input type="submit" class="btn btn-info" name="submit" value="search">
                </div>
            </form>
            <div>
                <a asp-controller="Exercises" asp-action="CreateExercise" class="btn btn-outline-success"><i class="fas fa-plus"></i>Thêm</a>
            </div>
        </div>
        <div class="table-overflow">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            STT
                        </th>
                        <th>
                            Bài tập
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.deadline)
                        </th>
                        <th>
                            Bài học
                        </th>
                        <th>
                            Tác giả
                        </th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="row-listcourses-admin">
                            <td class="counterCell">
                            </td>
                            <td>
                                Bài tập @Html.DisplayFor(modelItem => item.exerciseId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.deadline)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Lesson.title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AppUser.UserName)
                            </td>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.exerciseId"><i class="far fa-edit"></i></a> |
                                <a asp-action="DeleteExercise" asp-route-id="@item.exerciseId"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </section>
</main>
@*class="text-danger" onclick="return confirm('Bạn chắn chắn xóa chứ?')*@
<script>
    const active_lienhe = document.querySelector('#active--baitap')
    active_lienhe.classList.add('active--css')
    /*document.querySelector('#active--khoahoc').classList.remove('active--css')*/
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Courses_MVC/Courses_MVC/Views/Exercises/UpdateExercise.cshtml
@model Courses_MVC.Models.Exercise

@{
    ViewData["Title"] = "Chỉnh sửa bài luyện tập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main class="main">
    <div class="sidebar-admin">
        <partial name="_NavBar" />
    </div>
    <section class="section-add_course">
        <partial name="_AlertMessage" />
        <h1 class="text-center mt-3">Cập nhật bài luyện tập</h1>
        <div class="p-4">
            <form action="" class="form-update-course" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="exerciseId" />
                <div class="form-group">
                    <label asp-for="exerciseName" class="control-label"></label>
                    <input asp-for="exerciseName" class="form-control" />
                    <span asp-validation-for="exerciseName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="content" class="control-label"></label>
                    <textarea asp-for="content" class="form-control" required rows="5" id="content"></textarea>
                    <span asp-validation-for="content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="input" class="control-label"></label>
                    <textarea asp-for="input" class="form-control" required rows="5" id="input"></textarea>
                    <span asp-validation-for="input" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="output" class="control-label"></label>
                    <textarea asp-for="output" class="form-control" required rows="5" id="output"></textarea>
                    <span asp-validation-for="output" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="deadline" class="control-label"></label>
                    <input asp-for="deadline" class="form-control" />
                    <span asp-validation-for="deadline" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lessonId" class="control-label"></label>
                    <select asp-for="lessonId" class="form-control" asp-items="ViewBag.lessonId"></select>
                    <span asp-validation-for="lessonId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="userId" class="control-label">Tác giả</label>
                    <select asp-for="userId" class="form-control" asp-items="ViewBag.userId"></select>
                    <span asp-validation-for="userId" class="text-danger"></span>
                </div>
                <div class="form-row mb-4">
                    <div class="form-group col-md-6">
                        <input type="submit" name="submit" value="Cập nhật" class="btn btn-primary btn-block" />
                    </div>
                    <div class="form-group col-md-6">
                        <a asp-action="ListExerciseAdmin" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Trở về</a>
                    </div>
                </div>
            </form>
        </div>
    </section>
</main>
@{
    var summernote = new Courses_MVC.Models.Summernote("#content");
    var input = new Courses_MVC.Models.Summernote("#input", false);
    var output = new Courses_MVC.Models.Summernote("#output", false);

}
<partial name="_Summernote" model="summernote" />
<partial name="_Summernote" model="input" />
<partial name="_Summernote" model="output" />
<script>
    const active_lienhe = document.querySelector('#active--baihoc')
    active_lienhe.classList.add('active--css')
    /*document.querySelector('#active--khoahoc').classList.remove('active--css')*/
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}